# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a47258c9ad482cf846d61c7ad095b29e7ea27c671dea3cdbd4c13606796c54eea378a34ab815fb2bf8c56d3a93d40962ed871add76445b74c8ecf4cd0f04825a

test:
  secret_key_base: b11344a6a05475bd085c4106784e26fa2ec2bd446c22d4f03361d68618cc9addb4a9831b6f7ae6b097c78a72c0616f4acd697e23de59f7eac6823011d26fea17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
